In [31]:
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
from  dash import Dash, dcc, html, callback, Output, Input
#import dash_design_kit as ddk

In [32]:
df = pd.read_csv('gcpEconomicSectors.csv')
df.head()

,County,Agriculture_Forestry_and_Mining,Mining_and_Quarrying,Manufacturing,Electricity_supply,Water_supply_waste_collection,Construction,Wholesale_and_Retail_trade_repair_of_motor_vehicles,Transport_and_storage,Accommodation_and_food_service_activities,...,Real_Estate_activities,Professional_and_technical_services,Administrative_support_services,Public_administration_and_defence,Education,Human_health_and_social_work_activities,Other_service_activities,Financial_services_indirectly_measured,GCP,Year
0,BARINGO,19385,131,4106,114,386,1482,2149,8769,178,...,2846,1580,1046,8056,4721,3094,1478,373,61894,2018
1,BOMET,72044,647,11928,376,629,8879,1187,8917,802,...,3244,1894,959,8840,7686,2351,2342,451,133969,2018
2,BUNGOMA,73443,294,7755,653,1387,4567,9312,20623,1728,...,8841,3301,1724,13249,17370,4061,4493,1329,177336,2018
3,BUSIA,21951,307,2299,201,612,6483,2445,7550,137,...,3847,1589,805,8631,7341,2659,2963,513,71210,2018
4,ELGEYO MARAKWET,56910,506,2248,130,270,869,1891,8101,176,...,2763,693,475,5673,3757,2308,785,94,88863,2018

In [33]:
app= Dash(__name__)

In [34]:
# Line Graph of GCP vs Year, with a dropdown County
app.layout = html.Div([
    html.H1(children='KENYA GROSS COUNTY PRODUCT(2018-2020)',style={'textAlign':'center'}),
    dcc.Dropdown(df.County.unique(), 'Baringo', id='dropdown-selection'),
    dcc.Graph(id='graph-content')
])

@callback(
    Output('graph-content','figure'),
    Input('dropdown-selection', 'value')
)
def update_graph(value):
    dff = df[df.County==value]
    return px.line(dff, x='Year', y='GCP')

In [35]:
fig = px.bar(df.County)
app.layout = html.Div(children=[
    html.Div(children='''Bar Graph''', style={'textAlign':'center'}),
    dcc.Graph(id='example-graph',
              figure=fig
    )
    
])

In [36]:
if __name__ == '__main__':
    app.run_server(debug=True, jupyter_mode='tab')

Dash app running on http://127.0.0.1:8050/